name: bootpay_webview_flutter_web
description: A Flutter plugin that provides a WebView widget on web.
repository: https://github.com/bootpay/bootpay_webview_flutter_web
issue_tracker: https://github.com/bootpay/bootpay_webview_flutter_web/issues
version: 0.2.2+4

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

flutter:
  plugin:
    implements: bootpay_webview_flutter
    platforms:
      web:
        pluginClass: WebWebViewPlatform
        fileName: webview_flutter_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  bootpay_webview_flutter_platform_interface: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
