name: bootpay_webview_flutter_web
description: A Flutter plugin that provides a WebView widget on web.
repository: https://github.com/bootpay/bootpay_webview_flutter_web
issue_tracker: https://github.com/bootpay/bootpay_webview_flutter_web/issues
version: 0.1.0+4

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    implements: bootpay_webview_flutter
    platforms:
      web:
        pluginClass: WebWebViewPlatform
        fileName: webview_flutter_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  bootpay_webview_flutter_platform_interface: ^1.9.5

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
